# Generated by Django 5.2.13 on 2026-06-09 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customization',
            old_name='custom_text',
            new_name='image_url',
        ),
    ]
