# Generated by Django 5.2.13 on 2026-06-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customization',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('IN_REVIEW', 'In Review'), ('APPROVED', 'Approved'), ('PRODUCTION', 'In Production'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='designerassignment',
            name='status',
            field=models.CharField(blank=True, choices=[('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ASSIGNED', max_length=50, null=True),
        ),
    ]
