# Generated by Django 5.2.13 on 2026-06-08 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customization', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='designerassignment',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.orderitem'),
        ),
        migrations.AddField(
            model_name='designplacement',
            name='customization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customization.customization'),
        ),
    ]
