# Generated by Django 5.2.13 on 2026-06-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_is_bespoketeam_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designer',
            name='availability_status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('BUSY', 'Busy'), ('OFFLINE', 'Offline'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=50),
        ),
    ]
