# Generated by Django 5.2.13 on 2026-06-03 14:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_designer_availability_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcode',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='verificationcode',
            name='purpose',
            field=models.CharField(choices=[('verification', 'Account Verification'), ('reset', 'Password Reset')], default='verification', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('USER', 'User'), ('ADMIN', 'Admin'), ('BESPOKETEAM', 'Bespoke Team'), ('PARTNERS', 'Partners'), ('CUSTOMER', 'Customer')], default='CUSTOMER', max_length=20, verbose_name='user type'),
        ),
    ]
