# Generated by Django 6.0.5 on 2026-06-04 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_passwordresetotp_delete_verificationcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresetotp',
            name='created_at',
        ),
        migrations.AddField(
            model_name='passwordresetotp',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passwordresetotp',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_otp', to=settings.AUTH_USER_MODEL),
        ),
    ]
