# Generated by Django 5.2.13 on 2026-06-05 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_verificationcode_expires_at_verificationcode_purpose_and_more'),
        ('accounts', '0005_remove_passwordresetotp_created_at_and_more'),
    ]

    operations = [
    ]
